version: "3.9"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  pull_policy: never
  image: job_warehouse_discord:latest
  restart: always
  environment: &airflow-common-env
    AIRFLOW_HOME: /opt/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_AIRFLOW}
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW_CONN_TRINO_DEFAULT: trino://trino@trino:8080/default
    DBT_TARGET: airflow
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_AIRFLOW: ${DB_AIRFLOW}
    DB_JOB: ${DB_JOB}
    DB_TRINO: ${DB_TRINO}
    DB_NAME: ${DB_AIRFLOW}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/config/airflow.cfg:/opt/airflow/config/airflow.cfg
    - ./airflow/scripts:/opt/airflow/scripts
    - ./airflow/tasks:/opt/airflow/tasks
    - ./airflow/dbt_jobflow:/opt/airflow/dbt_jobflow
    - ./.env:/opt/airflow/.env
  depends_on: &airflow-common-depends-on
    postgresql_db:
      condition: service_healthy

services:
  postgresql_db:
    image: postgres:16.4
    container_name: postgresql_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_AIRFLOW}
      DB_JOB: ${DB_JOB}
      DB_TRINO: ${DB_TRINO}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/init_db/init.sql:/docker-entrypoint-initdb.d/01_create_databases.sql
      - ./postgresql/init_schema_table/init_schema_tables.sql:/docker-entrypoint-initdb.d/02_create_schema_tables_job_db.sql
      - ./postgresql/init_wh_catalog/init_catalog_tables.sql:/docker-entrypoint-initdb.d/03_create_catalog_tables_trino.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_AIRFLOW}"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      <<: *airflow-common-depends-on
    environment:
      <<: *airflow-common-env
    command: |
      bash -c '
      set -e

      echo "Waiting for database..."

      export PGPASSWORD="$DB_PASSWORD"

      until pg_isready \
        -h "$DB_HOST" \
        -p "$DB_PORT" \
        -U "$DB_USER" \
        -d "$DB_AIRFLOW"; do
          echo "Postgres not ready yet..."
          sleep 5
      done

      echo "Postgres is ready."

      airflow db migrate

      echo "Checking if admin user exists..."

      ADMIN_EXISTS=$(airflow users list | grep -c "$DB_USER" || wc -l)

      if ! airflow users get "$DB_USER" >/dev/null 2>&1; then
        echo "Creating admin user..."
        airflow users create \
          --username "$DB_USER" \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com \
          --password "$DB_PASSWORD"
      fi

      echo "Airflow init completed."
      '
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
      airflow-webserver:
        condition: service_healthy
    command: scheduler
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      until mc alias set minio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}; do
        sleep 2;
      done;
      mc mb -p minio/warehouse || true;
      mc mb -p minio/crawled-data || true;
      echo 'MinIO initialization completed';
      "
    restart: "no"

  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      minio-init:
        condition: service_completed_successfully
      postgresql_db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_TRINO}
      POSTGRES_JOB_DB: ${DB_JOB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - ./trino/etc:/etc/trino
    restart: always

  trino-init:
    image: trinodb/trino:latest
    container_name: trino-init
    depends_on:
      trino:
        condition: service_started
      postgresql_db:
        condition: service_healthy
    volumes:
      - ./trino/init_schema:/init_schema
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for Trino...';
      until trino --server http://trino:8080 --execute 'SELECT 1'; do
        sleep 3;
      done;

      echo 'Running init_schema.sql';
      trino --server http://trino:8080 --file /init_schema/init_schema.sql;
      echo 'Init schema completed';
      "
    restart: "no"

volumes:
  postgres_data:
  minio_data:
