include:
  - path: ./infra/postgresql/docker-compose.postgresql.yml
  - path: ./infra/minio/docker-compose.minio.yml
  - path: ./infra/airflow/docker-compose.airflow.yml
  - path: ./infra/trino/docker-compose.trino.yml
  - path: ./infra/chroma/docker-compose.chroma.yml
  - path: ./infra/redis/docker-compose.redis.yml
  - path: ./infra/mongodb/docker-compose.mongodb.yml
  - path: ./apps/api/docker-compose.api.yml
  - path: ./apps/bot/docker-compose.bot.yml

networks:
  default:
    driver: bridge
