services:
  trino:
    image: trinodb/trino:${TRINO_VERSION:-481}
    container_name: trino
    depends_on:
      minio-init:
        condition: service_completed_successfully
      postgresql_db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${DB_HOST:-postgresql_db}
      POSTGRES_PORT: ${DB_PORT:-5432}
      POSTGRES_DB: ${DB_TRINO:-catalog_wh}
      POSTGRES_JOB_DB: ${DB_JOB:-job_db}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      MINIO_USER: ${MINIO_USER:-user}
      MINIO_PASSWORD: ${MINIO_PASSWORD:-password}
    ports:
      - "${TRINO_HOST_PORT:-8081}:8080"
    volumes:
      - ./etc:/etc/trino
    restart: always

  trino-init:
    image: trinodb/trino:${TRINO_VERSION:-481}
    container_name: trino-init
    depends_on:
      trino:
        condition: service_started
      postgresql_db:
        condition: service_healthy
    volumes:
      - ./init_schema:/init_schema
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for Trino...';
      until trino --server http://trino:8080 --execute 'SELECT 1'; do
        sleep 3;
      done;

      echo 'Running init_schema.sql';
      trino --server http://trino:8080 --file /init_schema/init_schema.sql;
      echo 'Init schema completed';
      "
    restart: "no"
